#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/iphunter-core
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall iphunter-core
}

restart_service() {
    stop_service
    sleep 2
    start_service
}

reload_service() {
    # Reload config only (send SIGHUP if supported)
    killall -HUP iphunter-core 2>/dev/null || restart_service
}
